# This is a basic workflow to help you get started with Actions

name: lint-and-test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linter-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install deps
        run:  |
          python3 -m pip install --upgrade pip
          pip install poetry
          make install
      - name: lint
        run: make lint
      - name: test
        run: make pytest

